schema_version: 1

context:
  name: libmicrohttpd
  version: "1.0.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-${{ version }}.tar.gz
  sha256: 827250db649546cdb04bea01f5f0560f0edffde9130e256387d1f977242eaf98

build:
  number: 0
  skip: win

requirements:
  build:
    - if: unix
      then:
        - gnuconfig
        - pkg-config
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - make
  host:
    - gnutls
  run_exports:
    - ${{ pin_subpackage("libmicrohttpd", upper_bound="x.x") }}

tests:
  - script:
      - if: unix
        then:
          - test -f $PREFIX/lib/libmicrohttpd${SHLIB_EXT}
          - test -f $PREFIX/include/microhttpd.h
about:
  license: LGPL-2.0-or-later
  license_file: COPYING
  summary: Light HTTP/1.1 server library
  homepage: https://www.gnu.org/software/libmicrohttpd/

extra:
  recipe-maintainers:
    - xhochy
